import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Main from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills'

export default function Home() {
  return (
    <>
      <Head>
        <title>Kaio | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav.ico" />
      </Head>

      <main className="home">
        <Navbar/>
        <Main/>
        <About/>
        <Skills/>

      </main>
      
    </>
  )
}
